export const DATA_PRODUCTS = [
  {
    product_name: "Gelas",
    qty: 100,
    harga: 2000,
    tag: [
      {
        title: "1",
      },
      {
        title: "2",
      },
      {
        title: "3",
      },
      {
        title: "4",
      },
      {
        title: "5",
      },
    ],
  },
  {
    product_name: "Botol",
    qty: 100,
    harga: 1000,
    tag: [
      {
        title: "1",
      },
      {
        title: "2",
      },
      {
        title: "3",
      },
    ],
  },
  {
    product_name: "Toples",
    qty: 100,
    harga: 10000,
    tag: [
      {
        title: "1",
      },
      {
        title: "2",
      },
      {
        title: "3",
      },
      {
        title: "4",
      },
    ],
  },
];
